version: '2'

networks:
    default:
        external:
            name: "${COMPOSE_PROJECT_NAME}-network"

volumes:
    database:
        external:
            name: "${COMPOSE_PROJECT_NAME}-database"

services:
    nginx:
        container_name: "${COMPOSE_PROJECT_NAME}_nginx"
        image: ekyna/nginx
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ../../web:/var/www/web:ro
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            default:
                aliases:
                    - nginx

    php:
        container_name: "${COMPOSE_PROJECT_NAME}_php"
        image: ekyna/php7-fpm-dev
        volumes:
            - ../..:/var/www:rw
            - ./config/php-fpm.conf:/etc/php7/php-fpm.conf:ro
            - ./config/php.ini:/etc/php7/conf.d/90-custom.ini:ro
        environment:
            PHP_DOCKER_ACCESS: "1"
        networks:
            default:
                aliases:
                    - php

    mysql:
        container_name: "${COMPOSE_PROJECT_NAME}_mysql"
        image: ekyna/mysql
        env_file: ./config/mysql.env
        volumes:
            - database:/var/lib/mysql:rw
        networks:
            default:
                aliases:
                    - mysql
